#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-minitest_tu_shim
Version  : 1.3.3
Release  : 6
URL      : https://rubygems.org/downloads/minitest_tu_shim-1.3.3.gem
Source0  : https://rubygems.org/downloads/minitest_tu_shim-1.3.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-minitest_tu_shim-bin
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc
Patch1: 0001-Fix-minitest-version.patch

%description
= minitest_tu_shim
* http://rubyforge.org/projects/bfts
== DESCRIPTION:
minitest_tu_shim bridges the gap between the small and fast minitest
and ruby's huge and slow test/unit.

%package bin
Summary: bin components for the rubygem-minitest_tu_shim package.
Group: Binaries

%description bin
bin components for the rubygem-minitest_tu_shim package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n minitest_tu_shim-1.3.3
gem spec %{SOURCE0} -l --ruby > rubygem-minitest_tu_shim.gemspec
%patch1 -p1

%build
gem build rubygem-minitest_tu_shim.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
minitest_tu_shim-1.3.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/minitest_tu_shim-1.3.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/MiniTest/cdesc-MiniTest.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Module/tu_deprecate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Module/tu_deprecation_warning-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Assertions/assert_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Assertions/assert_nothing_raised-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Assertions/build_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Assertions/cdesc-Assertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Assertions/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/Error/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/TestCase/test_order-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/page-History_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/minitest_tu_shim-1.3.3/ri/page-README_txt.ri
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/bin/use_minitest
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/lib/test/unit.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/lib/test/unit/assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/lib/test/unit/deprecate.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/lib/test/unit/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/lib/test/unit/testcase.rb
/usr/lib64/ruby/gems/2.2.0/gems/minitest_tu_shim-1.3.3/test/test_mini_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/minitest_tu_shim-1.3.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/use_minitest
